name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  # === ЭТАП 1: ТЕСТИРОВАНИЕ ===
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код из репозитория
        uses: actions/checkout@v4

      - name: Настраиваем Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Укажи свою версию ноды

      - name: Устанавливаем пакеты
        run: npm install

      - name: Запускаем тесты
        run: npm run test # <-- Если команда выдаст ошибку, всё остановится!

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/luminary/frontend
            git pull origin main
            docker compose up -d --build
